# Cloud Build configuration for Web only
steps:
  # Build and push Web Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jackson-ideas-web:latest', '-f', 'Dockerfile.web', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jackson-ideas-web:latest']
  
  # Deploy Web to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'jackson-ideas-web'
      - '--image=gcr.io/$PROJECT_ID/jackson-ideas-web:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production,ApiSettings__BaseUrl=https://jackson-ideas.onrender.com'

images:
  - 'gcr.io/$PROJECT_ID/jackson-ideas-web:latest'

timeout: '600s'