services:
  # API Service
  - type: web
    name: jackson-ideas-api
    runtime: docker
    dockerfilePath: Dockerfile.api.render
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: PORT
        value: 8080
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/app/jackson_ideas.db
      - key: Jwt__SecretKey
        generateValue: true
      - key: Jwt__Issuer
        value: https://jackson-ideas-api.onrender.com
      - key: Jwt__Audience  
        value: https://jackson-ideas-web.onrender.com
      - key: Cors__AllowedOrigins__0
        value: https://jackson-ideas-web.onrender.com
      - key: Cors__AllowedOrigins__1
        value: http://localhost:4000
    healthCheckPath: /health
    buildCommand: echo "Using Docker build"
    startCommand: dotnet Jackson.Ideas.Api.dll

  # Web Service
  - type: web
    name: jackson-ideas-web
    runtime: docker
    dockerfilePath: Dockerfile.web
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: PORT
        value: 8080
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/app/jackson_ideas.db
      - key: ApiBaseUrl
        value: https://jackson-ideas-api.onrender.com
      - key: Jwt__SecretKey
        generateValue: true
      - key: Jwt__Issuer
        value: https://jackson-ideas-api.onrender.com
      - key: Jwt__Audience
        value: https://jackson-ideas-web.onrender.com
      - key: UseMockAuthentication
        value: "false"
    healthCheckPath: /health
    buildCommand: echo "Using Docker build"
    startCommand: dotnet Jackson.Ideas.Web.dll