services:
  # Ideas Matter Web Application
  - type: web
    name: jaxsun-ideasmatter
    runtime: docker
    dockerfilePath: Dockerfile.render
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: PORT
        value: 10000
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/app/data/jackson_ideas.db
      - key: UseMockAuthentication
        value: true
      - key: DemoMode__Enabled
        value: true
      - key: DemoMode__UseRealAI
        value: false
      - key: DemoMode__SimulateProcessingDelays
        value: true
      - key: Jwt__SecretKey
        generateValue: true
      - key: Jwt__Issuer
        value: https://jaxsun-ideasmatter.onrender.com
      - key: Jwt__Audience
        value: https://jaxsun-ideasmatter.onrender.com
    healthCheckPath: /healthz