services:
  # Main Web Application (UI + API combined)
  - type: web
    name: jaxsun-ideasmatter
    runtime: docker
    dockerfilePath: Dockerfile.web
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: PORT
        value: 8080
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/app/jackson_ideas.db
      - key: Jwt__SecretKey
        generateValue: true
      - key: Jwt__Issuer
        value: https://jaxsun-ideasmatter.onrender.com
      - key: Jwt__Audience
        value: https://jaxsun-ideasmatter.onrender.com
      - key: UseMockAuthentication
        value: true
    healthCheckPath: /health
    buildCommand: echo "Using Docker build"
    startCommand: dotnet Jackson.Ideas.Web.dll