#!/bin/bash

# Script to create Ideas Matter vision in GitHub

echo "========================================="
echo "Ideas Matter Vision Creation Script"
echo "========================================="
echo ""
echo "This script will help you create the Ideas Matter vision in GitHub."
echo ""
echo "Vision document location: Commands/docs/visions/ideas-matter/vision.md"
echo ""
echo "You have two options to create the vision:"
echo ""
echo "Option 1: Using GitHub CLI (if installed)"
echo "-----------------------------------------"
echo "Run this command:"
echo ""
echo "gh workflow run create-vision.yml \\"
echo "  -f product_name='Ideas Matter' \\"
echo "  -f vision_file_path='Commands/docs/visions/ideas-matter/vision.md' \\"
echo "  -f preview=false"
echo ""
echo "For preview mode (no changes), use:"
echo ""
echo "gh workflow run create-vision.yml \\"
echo "  -f product_name='Ideas Matter' \\"
echo "  -f vision_file_path='Commands/docs/visions/ideas-matter/vision.md' \\"
echo "  -f preview=true"
echo ""
echo "Option 2: Using GitHub Web Interface"
echo "------------------------------------"
echo "1. Go to your repository on GitHub"
echo "2. Click on 'Actions' tab"
echo "3. Select 'Create Product Vision' workflow"
echo "4. Click 'Run workflow'"
echo "5. Fill in:"
echo "   - Product name: Ideas Matter"
echo "   - Vision file path: Commands/docs/visions/ideas-matter/vision.md"
echo "   - Preview: false (or true for preview)"
echo "6. Click 'Run workflow'"
echo ""
echo "What this will create:"
echo "- GitHub Issue with vision summary (labeled 'vision')"
echo "- GitHub Project for 'Ideas Matter Development'"
echo "- Pin the vision issue to repository"
echo "- Create all necessary labels"
echo "- Commit the vision document to the repository"
echo ""